[build-system]
requires = ["meson-python", "pybind11"]
build-backend = "mesonpy"

[project]
name = "frxx"
version = "0.1.5.3"
description = "Utils to process and visualize I/Q data from a weather radar."
readme = "README.md"
requires-python = ">=3.10"
license = "LGPL-3.0-or-later"
license-files = [
    "LICENSE",
    "THIRD_PARTY_NOTICES.md",
    "LICENSES/Eigen/*",
    "LICENSES/pocketfft/*",
]
authors = [
  { name="Ameya Naik" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
]
dependencies = [
    "platformdirs",
    "numpy",
    "matplotlib>=3.10.9",
    "pandas",
    "pytz",
    "netCDF4",
    "xarray",
    "requests",
    "arm_pyart",
    "cmweather",
]

[project.scripts]
frxx = "frxx.cli:main"

[project.urls]
"Homepage" = "https://github.com/aeol1an/frxx"
"Bug Tracker" = "https://github.com/aeol1an/frxx/issues"
