python_sources = files(
    '__init__.py',
    'angleSplitter.py',
    'cfUtils.py',
    'coordConvert.py',
    'freqResolution.py',
    'numbaHelpers.py',
    'numbaWindows.py',
    'pathUtils.py',
    'sourceFileUtils.py',
    'stringUtils.py'
)

py.install_sources(
    python_sources,
    subdir: 'frxx/utils',
    install_tag: 'runtime'
)
