from typing import TYPE_CHECKING

import numpy as np
from numpy.typing import NDArray

if TYPE_CHECKING:
    def rectangular(N: int) -> NDArray[np.float64]: ...
    def hanning(N: int) -> NDArray[np.float64]: ...
    def hamming(N: int) -> NDArray[np.float64]: ...
    def blackman(N: int) -> NDArray[np.float64]: ...
    def bartlett(N: int) -> NDArray[np.float64]: ...
else:
    from ._numbaWindows import bartlett, blackman, hamming, hanning, rectangular
