python_sources = files(
    '__init__.py',
    'cmaps.py',
    'defaultPlotParameters.py',
    'iDealias.py',
    'iPyart.py',
    'iSpectrumDealias.py',
    'plotFigAsImg.py',
    'plotMoments.py',
    'plotSpectra.py',
    'polarGridPlotting.py'
)

py.install_sources(
    python_sources,
    subdir: 'frxx/viz',
    install_tag: 'runtime'
)
