from abc import ABC, abstractmethod
from typing import Optional

import numpy as np
import xarray as xr

class frxxData(ABC):
	def __init__(self):
		self.ds = xr.Dataset()

		self.rootAttrs = {
			"Conventions": "frxxdata",
			"institution": "University of Oklahoma",
			"history": "",
			"comment": "Generated by frxx (Author: Ameya Naik, https://github.com/aeol1an).",
			"time_coverage_start": "tbd",
			"time_coverage_end": "tbd",
			"start_datetime": "tbd",
			"end_datetime": "tbd",
		}
		for key, value in self.rootAttrs.items():
			self.ds.attrs[key] = value

		self.ds = self.ds.assign_coords(
			string_length_8=np.arange(8),
			string_length_32=np.arange(32),
		)

		self.requiredBools = {
			#All of these are required true
			"instrument_name": False,
			"source": False, #radarkit
			"volume": False,
			"sweep": False,
			"time": False,
			"range": False,
			"position": False,
			"scanning_strategy": False,
			"target_angle": False,
			"azimuth": False,
			"elevation": False,
			"pulse_width": False,
			"prt": False,
			"wavelength": False
		}

		self.optionalBools = {
			#None of these are require true, but are helpful for documentation
			"history": False,
			"addtl_comments": False,
		}

	@abstractmethod
	def constructFilename(self):
		pass

	@abstractmethod
	def constructTimeStr(self, index: Optional[int] = None):
		pass

	@abstractmethod
	def validateSelf(self):
		pass