from abc import ABC, abstractmethod
from typing import Optional, List, TypeVar, Generic

from warnings import warn

from pathlib import Path

from numpy.typing import NDArray
from datetime import datetime, timedelta
import pytz

import numpy as np
import xarray as xr

_FILL_VALUES = {
	"int16": np.iinfo(np.int16).min,
	"int32": np.iinfo(np.int32).min,
	"float32": -9999.0,
	"float64": -9999.0,
	"|S1": b' '
}

T = TypeVar('T', bound='frxxData')
class frxxData(ABC, Generic[T]):
	def __init__(self):
		self.ds = xr.Dataset()

		self.rootAttrs = {
			"frxx_data_type": "",
			"Conventions": "",
			"history": "",
			"comment": "Generated by frxx (Author: Ameya Naik, https://github.com/aeol1an).",
		}
		for key, value in self.rootAttrs.items():
			self.ds.attrs[key] = value

		self.ds = self.ds.assign_coords(
			string_length_8=np.arange(8),
			string_length_32=np.arange(32),
		)

		self.requiredBools = {
			#All of these are required true
			"instrument_name": False,
			"volume": False,
			"sweep": False,
			"time": False,
			"range": False,
			"position": False,
			"scanning_strategy": False,
			"azimuth": False,
			"elevation": False,
			"pulse_width": False,
			"prt": False,
			"wavelength": False,
		}

		self.optionalBools = {
			#None of these are require true, but are helpful for documentation
			"history": False,
			"addtl_comments": False,
		}

		self.numDataVars = 0

	def setInstrument(self, name: str, institution: str, source: str):
		self.ds.attrs["instrument_name"] = name
		self.ds.attrs["institution"] = institution
		self.ds.attrs["source"] = source
		self.requiredBools["instrument_name"] = True

	def setVolume(self, volNum: int = 0):
		self.ds["volume_number"] = xr.DataArray(
			data = volNum,
			dims = [],
			attrs = {
				"standard_name": "data_volume_index_number",
			}
		)
		self.ds["volume_number"].encoding = {
			"dtype": "int32",
			"_FillValue": _FILL_VALUES["int32"]
		}

		self.requiredBools["volume"] = True
		
	def setTime(self, unixTimeArr: NDArray[np.float64], time_zone: str = 'zulu'):
		if (unixTimeArr.dtype != np.float64):
			raise TypeError("Expected array of np.float64")
		
		startTime = unixTimeArr[0]
		endTime = unixTimeArr[-1]
		
		timeVar = unixTimeArr - startTime
		
		startTimeStr = datetime.fromtimestamp(startTime, tz=pytz.timezone(time_zone))\
			.astimezone(pytz.utc).isoformat()
		endTimeStr = datetime.fromtimestamp(endTime, tz=pytz.timezone(time_zone))\
			.astimezone(pytz.utc).isoformat()
			
		self.ds.attrs["time_coverage_start"] = startTimeStr.replace('+00:00', 'Z')
		self.ds.attrs["start_datetime"] = startTimeStr
		self.ds.attrs["time_coverage_end"] = endTimeStr.replace('+00:00', 'Z')
		self.ds.attrs["end_datetime"] = endTimeStr
		
		paddedStartTime = startTimeStr.replace('+00:00', 'Z') +\
			(len(self.ds["string_length_32"]) - len(startTimeStr.replace('+00:00', 'Z')))*' '
		paddedEndTime = endTimeStr.replace('+00:00', 'Z') +\
			(len(self.ds["string_length_32"])- len(endTimeStr.replace('+00:00', 'Z')))*' '
		
		self.ds["time_coverage_start"] = xr.DataArray(
			data = np.array([c for c in paddedStartTime], dtype="|S1"),
			dims = ["string_length_32"],
			attrs = {
				"standard_name": "data_volume_start_time_utc",
				"comment": "ray times are relative to start time in secs",
			}
		)
		self.ds["time_coverage_start"].encoding = {
			"dtype": "|S1",
			"_FillValue": b' ',
		}
		self.ds["time_coverage_end"] = xr.DataArray(
			data = np.array([c for c in paddedEndTime], dtype="|S1"),
			dims = ["string_length_32"],
			attrs = {
				"standard_name": "data_volume_end_time_utc",
				"comment": "ray times are relative to start time in secondss",
			},
		)
		self.ds["time_coverage_end"].encoding = {
			"dtype": "|S1",
			"_FillValue": b' ',
		}
		
		self.ds = self.ds.assign_coords(time=timeVar)
		self.ds["time"].attrs = {
			"units": "seconds since " + startTimeStr.replace('+00:00', 'Z'),
			"standard_name": "time",
			"long_name": "time in seconds since volume start",
		}
		self.ds["time"].encoding = {
			"dtype": "float64",
			"_FillValue": -9999.0
		}
		
		self.requiredBools["time"] = True

	def setSweep(self, sweepNum: int = 0):
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime before this.")
		
		self.ds = self.ds.assign_coords(sweep=np.arange(1))

		self.ds["sweep_number"] = xr.DataArray(
			data = np.array([sweepNum], dtype=np.int32),
			dims = ["sweep"],
			attrs = {
				"long_name": "sweep_index_number_0_based",
			}
		)
		self.ds["sweep_number"].encoding = {
			"dtype": "int32",
			"_FillValue": _FILL_VALUES["int32"]
		}

		nRays = len(self.ds["time"])
		self.ds["sweep_start_ray_index"] = xr.DataArray(
			data = np.array([0], dtype=np.int32),
			dims = ["sweep"],
			attrs = {
				"long_name": "index_of_first_ray_in_sweep",
			}
		)
		self.ds["sweep_start_ray_index"].encoding = {
			"dtype": "int32",
			"_FillValue": _FILL_VALUES["int32"]
		}
		self.ds["sweep_end_ray_index"] = xr.DataArray(
			data = np.array([nRays-1], dtype=np.int32),
			dims = ["sweep"],
			attrs = {
				"long_name": "index_of_last_ray_in_sweep",
			}
		)
		self.ds["sweep_end_ray_index"].encoding = {
			"dtype": "int32",
			"_FillValue": _FILL_VALUES["int32"]
		}

		self.requiredBools["sweep"] = True


	def setRange(self, rangeGates: NDArray[np.float32], spacingIsConstant: bool):
		if (rangeGates.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		
		firstGate = np.rint(rangeGates[0])
		dG = np.rint(rangeGates[1]-rangeGates[0])
		
		self.ds = self.ds.assign_coords(range=rangeGates)

		self.ds["range"].attrs = {
			"units": "meters",
			"long_name": "Range from instrument to center of gate",
			"spacing_is_constant": "true" if spacingIsConstant else "false",
			"meters_to_center_of_first_gate": str(firstGate),
			"meters_between_gates": str(dG) if spacingIsConstant else "non-uniform"
		}
		self.ds["range"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["range"] = True
		
	def setPosition(self, lat: float, lon: float, altitude: float):
		if lat < -90 or lat > 90:
			raise ValueError(f'Latitude {lat} out of -90 to 90 deg range.')
		if lon < -180 or lon > 180:
			raise ValueError(f'Longitude {lon} out of -180 to 180 deg range.')
		if altitude < 0:
			raise ValueError('Altitude cannot be less than 0.')

		self.ds["latitude"] = xr.DataArray(
			data = np.array(lat, dtype=np.float64),
			dims = [],
			attrs = {
				"units": "degrees_north",
				"long_name": "latitude"
			}
		)
		self.ds["latitude"].encoding = {
			"dtype": "float64",
			"_FillValue": _FILL_VALUES["float64"]
		}

		self.ds["longitude"] = xr.DataArray(
			data = np.array(lon, dtype=np.float64),
			dims = [],
			attrs = {
				"units": "degrees_east",
				"long_name": "longitude"
			}
		)
		self.ds["longitude"].encoding = {
			"dtype": "float64",
			"_FillValue": _FILL_VALUES["float64"]
		}

		self.ds["altitude"] = xr.DataArray(
			data = np.array(altitude, dtype=np.float64),
			dims = [],
			attrs = {
				"units": "meters_agl",
				"long_name": "altitude"
			}
		)
		self.ds["altitude"].encoding = {
			"dtype": "float64",
			"_FillValue": _FILL_VALUES["float64"]
		}
		
		self.requiredBools["position"] = True
		
	def setScanningStrategy(self, strategy: str, targetAngle: float):
		if strategy == "ppi":
			if targetAngle < 0 or targetAngle > 90:
				raise ValueError("Radar dish shouldn't be pointing into "
									"the floor or greater than vertical.")
			mode_str = 'azimuth_surveillance'
			mode_str += (len(self.ds["string_length_32"])- len(mode_str))*' '
			mode_str = np.array([[c for c in mode_str]], dtype='|S1')
			fixed_angle_units = "elevation degrees"
		else:
			raise ValueError("Sorry, only ppi mode supported for now.")
		
		self.ds["sweep_mode"] = xr.DataArray(
			data = mode_str,
			dims = ["sweep", "string_length_32"],
			attrs = {
				"long_name": "scan_mode_for_sweep"
			}
		)
		self.ds["sweep_mode"].encoding = {
			"dtype": '|S1',
			"_FillValue": _FILL_VALUES["|S1"]
		}

		self.ds["fixed_angle"] = xr.DataArray(
			data = np.array([targetAngle], dtype=np.float32),
			dims = ["sweep"],
			attrs = {
				"units": fixed_angle_units,
				"long_name": "ray_target_fixed_angle"
			}
		)
		self.ds["fixed_angle"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["scanning_strategy"] = True
	
	
	def setAzimuth(self, azimuths: NDArray[np.float32]):
		if (azimuths.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime() before this function.")
		if len(azimuths) != len(self.ds["time"]):
			raise RuntimeError("Number of azimuths need to measure number "
							   "of rays from setTime() function call. "
							   f'For this file, that is {len(self.ds["time"])} rays.')
		
		self.ds["azimuth"] = xr.DataArray(
			data = azimuths,
			dims = ["time"],
			attrs = {
				"units": "degrees",
				"long_name": "ray_azimuth_angle"
			}
		)
		self.ds["azimuth"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["azimuth"] = True
		
	def setElevation(self, elevations: NDArray[np.float32]):
		if (elevations.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime() before this function.")
		if len(elevations) != len(self.ds["time"]):
			raise RuntimeError("Number of elevations need to measure number "
							   "of rays from setTime() function call. "
							   f'For this file, that is {len(self.ds["time"])} rays.')
			
		self.ds["elevation"] = xr.DataArray(
			data = elevations,
			dims = ["time"],
			attrs = {
				"units": "degrees",
				"long_name": "ray_elevation_angle"
			}
		)
		self.ds["elevation"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["elevation"] = True
	
	def setPulseWidthSeconds(self, pulseWidths: NDArray[np.float32]):
		if (pulseWidths.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime() before this function.")
		if len(pulseWidths) != len(self.ds["time"]):
			raise RuntimeError("Number of pulse widths need to measure number "
							   "of rays from setTime() function call. "
							   f'For this file, that is {len(self.ds["time"])} rays.')
			
		self.ds["pulse_width"] = xr.DataArray(
			data = pulseWidths,
			dims = ["time"],
			attrs = {
				"units": "seconds",
				"long_name": "transmitter_pulse_width"
			}
		)
		self.ds["pulse_width"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["pulse_width"] = True
		
	def setPrtSeconds(self, pulseRepetitionTimes: NDArray[np.float32]):
		if (pulseRepetitionTimes.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime() before this function.")
		if len(pulseRepetitionTimes) != len(self.ds["time"]):
			raise RuntimeError("Number of prt values need to measure number "
							   "of rays from setTime() function call. "
							   f'For this file, that is {len(self.ds["time"])} rays.')
			
		self.ds["prt"] = xr.DataArray(
			data = pulseRepetitionTimes,
			dims = ["time"],
			attrs = {
				"units": "seconds",
				"long_name": "pulse_repetition_time"
			}
		)
		self.ds["prt"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
		
		self.requiredBools["prt"] = True
		
	def setWavelengthMeters(self, wavelengths: NDArray[np.float32]):
		if (wavelengths.dtype != np.float32):
			raise TypeError("Expected array of np.float32")
		if not self.requiredBools["time"]:
			raise RuntimeError("Need to call setTime() before this function.")
		if not self.requiredBools["prt"]:
			raise RuntimeError("Need to call setPrtSeconds() before this function, "
							   "for nyquist velocity calculation.")
		if len(wavelengths) != len(self.ds["time"]):
			raise RuntimeError("Number of wavelength values need to measure number "
							   "of rays from setTime() function call. "
							   f'For this file, that is {len(self.ds["time"])} rays.')
		
		self.ds["wavelength"] = xr.DataArray(
			data = wavelengths,
			dims = ["time"],
			attrs = {
				"units": "meters",
				"long_name": "radar_wavelength"
			}
		)
		self.ds["wavelength"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}

		self.ds["nyquist_velocity"] = xr.DataArray(
			data = (0.25*wavelengths/self.ds["prt"].values),
			dims = ["time"],
			attrs = {
				"units": "meters_per_second",
				"long_name": "unambiguous_doppler_velocity"
			}
		)
		self.ds["nyquist_velocity"].encoding = {
			"dtype": "float32",
			"_FillValue": _FILL_VALUES["float32"]
		}
			
		self.requiredBools["wavelength"] = True

	def appendHistory(self, history: str):
		self.rootAttrs["history"] += " "+history
		self.optionalBools["history"] = True

	def appendComments(self, comments: str):
		self.rootAttrs["comment"] += " "+comments
		self.optionalBools["addtl_comments"] = True

	@abstractmethod
	def addDataField(self, name: str, data: NDArray, dims: List[str], attrs, encoding):
		pass
	def _incDataCounts(self):
		self.numDataVars += 1
	def _constructDataArray(self, data: NDArray, dims: List[str], attrs, encoding) -> xr.DataArray:
		da = xr.DataArray(
			data = data,
			dims = dims,
			attrs = attrs
		)
		da.encoding = encoding
		return da

	@abstractmethod
	def constructFilename(self) -> str:
		pass
	def _constructFilename(self, prefix: str) -> str:
		if not self.requiredBools["instrument_name"]:
			raise RuntimeError("Instrument name has not been set yet.")
		if not self.requiredBools["time"]:
			raise RuntimeError("Time has not been set yet")
		
		dt = datetime.fromisoformat(self.ds.attrs["start_datetime"])
		formatted = dt.strftime("%Y%m%d_%H%M%S") + f".{dt.microsecond // 1000:03d}"
		return prefix+f".{formatted}_{self.ds.attrs['instrument_name']}.nc"

	def constructTimeStr(self, index: Optional[int] = 0):
		if not self.requiredBools["time"]:
			raise RuntimeError("Time has not been set yet")
		
		dt_start = datetime.fromisoformat(self.ds.attrs["start_datetime"]).astimezone(pytz.utc)
		dt = dt_start + timedelta(seconds=self.ds["time"].values[index].item())

		return dt.strftime('%m/%d/%Y %H:%M:%S Z')

	@abstractmethod
	def checkRequiredFields(self):
		pass
	def _checkAttrs(self, attrs: List[str], notEmpty: bool = True):
		for attr in attrs:
			if attr not in self.ds.attrs:
				print(f"{attr} not in attributes.")
				return False
			elif notEmpty and self.ds.attrs[attr] == "":
				return False
		return True

	def _checkVars(self, vars: List[str], notBad: bool = True):
		for var in vars:
			if var not in self.ds:
				print(f"{var} either doesn't exist")
				return False
			elif notBad and not np.all(np.isfinite(self.ds[var].values)):
				print(f"{var} has some nan or inf values.")
				return False
		return True
	def _checkRequiredFields(self):
		#setInstrumentName function
		attrs = ["instrument_name", "institution", "source"]
		self.requiredBools["instrument_name"] = self._checkAttrs(attrs)
		
		#setVolume function
		vars = ["volume_number"]
		self.requiredBools["volume"] = self._checkVars(vars)

		#setTime function
		attrs = ["time_coverage_start", "time_coverage_end", "start_datetime", "end_datetime"]
		strVars = ["time_coverage_start", "time_coverage_end"]
		vars = ["time"]
		self.requiredBools["time"] = (
			self._checkAttrs(attrs) 
			and self._checkVars(strVars, False) 
			and self._checkVars(vars)
		)

		#setSweep function
		vars = ["sweep", "sweep_number", "sweep_start_ray_index", "sweep_end_ray_index"]
		self.requiredBools["sweep"] = self._checkVars(vars)

		#setRange function
		vars = ["range"]
		self.requiredBools["range"] = self._checkVars(vars)

		#setPosition function
		vars = ["latitude", "longitude", "altitude"]
		self.requiredBools["position"] = self._checkVars(vars)

		#setScanningStrategy function
		strVars = ["sweep_mode"]
		vars = ["fixed_angle"]
		self.requiredBools["scanning_strategy"] = (
			self._checkVars(strVars, False)
			and self._checkVars(vars)
		)

		#setAzimuth function
		vars = ["azimuth"]
		self.requiredBools["azimuth"] = self._checkVars(vars)

		#setElevation function
		vars = ["elevation"]
		self.requiredBools["elevation"] = self._checkVars(vars)

		#setPulseWidth function
		vars = ["pulse_width"]
		self.requiredBools["pulse_width"] = self._checkVars(vars)

		#setPrt function
		vars = ["prt"]
		self.requiredBools["prt"] = self._checkVars(vars)

		#setWavelength function
		vars = ["wavelength", "nyquist_velocity"]
		self.requiredBools["wavelength"] = self._checkVars(vars)

	@abstractmethod
	def validateSelf(self) -> bool:
		pass
	def _validateSelf(self) -> bool:
		requiredBools = all(self.requiredBools.values())
		if not requiredBools:
			print("Some required bools have not been set.")
			return False
		return True
	
	@abstractmethod
	def concat(self, other: T) -> T:
		pass
	def _alignTime(self, otherDs: xr.Dataset) -> xr.Dataset:
		selfStart = datetime.fromisoformat(self.ds.attrs["start_datetime"])
		otherStart = datetime.fromisoformat(otherDs.attrs["start_datetime"])
		
		offset_seconds = (otherStart - selfStart).total_seconds()
		
		otherDs = otherDs.assign_coords(time=otherDs["time"] + offset_seconds)
		otherDs["time"].attrs["units"] = self.ds["time"].attrs["units"]

		return otherDs
	def _alignSweep(self, otherDs: xr.Dataset) -> xr.Dataset:
		lastSweep = self.ds["sweep"].values[-1]
		otherDs = otherDs.assign_coords(sweep=otherDs["sweep"] + lastSweep+1)
		
		lastSweepNumber = self.ds["sweep_number"].values[-1]
		otherDs["sweep_number"].data = otherDs["sweep_number"] + lastSweepNumber+1
		
		timeLength = len(self.ds["time"])
		otherDs["sweep_start_ray_index"].data = otherDs["sweep_start_ray_index"].values + timeLength
		otherDs["sweep_end_ray_index"].data = otherDs["sweep_end_ray_index"].values + timeLength

		return otherDs
	def _concat(self, other: "frxxData") -> xr.Dataset:
		if not self.validateSelf():
			raise RuntimeError("First operand seems to be invalid.")
		if not other.validateSelf():
			raise RuntimeError("Second operand seems to be invalid.")

		selfDsCpy = self.ds.copy(deep=False)
		otherDsCpy = other.ds.copy(deep=False)

		otherDsCpy = self._alignTime(otherDsCpy)
		otherDsCpy = self._alignSweep(otherDsCpy)

		selfDsCpy.attrs["end_datetime"] = otherDsCpy.attrs["end_datetime"]
		selfDsCpy.attrs["time_coverage_end"] = otherDsCpy.attrs["time_coverage_end"]
		selfDsCpy["time_coverage_end"].values = otherDsCpy["time_coverage_end"].values

		if set(selfDsCpy.variables) != set(otherDsCpy.variables):
			raise ValueError(f"Variable mismatch: {set(selfDsCpy.variables)} vs {set(otherDsCpy.variables)}")

		merged = xr.concat(
			[selfDsCpy, otherDsCpy], 
			dim = "time",
			data_vars="minimal",
			coords='minimal',
			compat='override'
		)
		for var in merged.variables:
			if "sweep" in merged[var].dims:
				if var == "sweep":
					#dont need to modify the coordinate itself
					continue
				merged[var].loc[{"sweep":otherDsCpy["sweep"].values}] = otherDsCpy[var].values
		
		if np.all(np.diff(merged["time"])>0):
			warn("Time is not non-decreasing! frxxData.concat should be used for adjacent.")

		if type(merged) != xr.Dataset:
			raise TypeError("Something went wrong. Somehow we have a dataarray.")

		return merged